spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supermercadito?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

